version: "3.7"
services:

  proxy:
    build:
      context: ../
      dockerfile: example/Dockerfile-proxy
    #networks:
    #  - envoymesh
    network_mode: bridge
    expose:
      - "10000"
      - "9901"
    ports:
      - "10000:10000"
      - "9901:9901"

#  web_service:
#    build:
#      context: .
#      dockerfile: Dockerfile-web-service
#    networks:
#      envoymesh:
#        aliases:
#          - web_service
#    expose:
#      - "80"
#    ports:
#      - "8080:80"

#networks:
#  envoymesh: {}
